[misc]

splashscreen = true
f3 = false
crash_on_esc = false
blue_screen_of_death = true

# General configurations that affect all screens.

[general]

event_handle_per_frame = 30
load_per_frame = 20

list_wrap = false

# The whole init won't load if any error occurrs.
strict_deserialization = false

props =     { visible = true , opacity = 255 }
tiles =     { visible = true , opacity = 255 }
water =     { visible = true , opacity =  70 }
materials = { visible = true , opacity = 255 }
grid =      { visible = false, opacity =  90 }

[general.prerendering]

# If 'palette' is enabled, 'tinted' and 'preview' will be ignored.

tiles = { tinted = true, preview = true, palette = false }
props = { tinted = true, palette = false }
materials = { palette = false }
shadows = false

# Per-screen configurations

[page.main]
[page.geometry]

basic_view = true # The classic RGB level view.

# Requires basic_view to be enabled.
# opacity: 0 - 255
# 'inherit' means take the setting from [general].
props = { inherit = true, visible = true, opacity = 255 }
tiles = { inherit = true, visible = true, opacity = 255 }
water = { inherit = true, visible = true, opacity =  70 }
materials = { visible = true, opacity =  255 }
grid =      { inherit = false, visible = false, opacity =  90 }

[page.geometry.basic_view_colors]

layer1 = { r = 255, g = 255, b = 255, a = 255 }
layer2 = { r = 0, g = 255, b = 0, a = 80 }
layer3 = { r = 255, g = 0, b = 0, a = 80 }
water = { r = 0, g = 0, b = 255, a = 70 }

[page.tiles]

props = { inherit = true, visible = true, opacity = 255 }
tiles = { inherit = true, visible = true, opacity = 255 }
water = { inherit = true, visible = true, opacity = 70 }
materials = { visible = true, opacity = 255 }
grid =      { inherit = true, visible = false, opacity =  90 }

[page.cameras]

props = { inherit = true, visible = true, opacity = 255 }
tiles = { inherit = true, visible = true, opacity = 255 }
water = { inherit = true, visible = true, opacity = 70 }
materials = { visible = true, opacity = 255 }
grid =      { inherit = true, visible = false, opacity =  90 }

[page.light]

props = { inherit = true, visible = true, opacity = 255 }
tiles = { inherit = true, visible = true, opacity = 255 }
water = { inherit = true, visible = true, opacity = 70 }
materials = { visible = true, opacity = 255 }
grid =      { inherit = true, visible = false, opacity =  90 }

[page.effects]

props = { inherit = true, visible = true, opacity = 255 }
tiles = { inherit = true, visible = true, opacity = 255 }
water = { inherit = true, visible = true, opacity = 70 }
materials = { visible = true, opacity = 255 }
grid =      { inherit = true, visible = false, opacity =  90 }

canvas = { r = 255, g = 0, b = 255, a = 100 }
effect = { r = 0, g = 255, b = 0, a = 120 }

[page.props]

props = { inherit = true, visible = true, opacity = 255 }
tiles = { inherit = true, visible = true, opacity = 255 }
water = { inherit = true, visible = true, opacity = 70 }
materials = { visible = true, opacity = 255 }
grid =      { inherit = true, visible = false, opacity =  90 }


[paths.data]

# if default is true, ignore path 
default = true 
path = "Data"

[paths.cast]

# if inherit is true, ignore path
inherit = true
path = "Data/Cast"

[paths.assets]

# if default is true, ignore path 
default = true
path = "Assets"

[[paths.inits.materials]]

# Add a path to a materials init file

[[paths.inits.tiles]]

# Add a path to a tiles init file

[[paths.inits.props]]

# Add a path to a props init file

# Shortcuts that work across screens.

[shortcuts.global.pages]

# Each number maps to an enum defined in raylib.h
# 48..57 = KEY_ONE..KEY_NINE

start       = { key = 48, ctrl = false, shift = false, alt = false, held = false }
main        = { key = 49, ctrl = false, shift = false, alt = false, held = false }
geometry    = { key = 50, ctrl = false, shift = false, alt = false, held = false }
tiles       = { key = 51, ctrl = false, shift = false, alt = false, held = false }
cameras     = { key = 52, ctrl = false, shift = false, alt = false, held = false }
light       = { key = 53, ctrl = false, shift = false, alt = false, held = false }
dimensions  = { key = 54, ctrl = false, shift = false, alt = false, held = false }
effects     = { key = 55, ctrl = false, shift = false, alt = false, held = false }
props       = { key = 56, ctrl = false, shift = false, alt = false, held = false }
settings    = { key = 57, ctrl = false, shift = false, alt = false, held = false }

# Shortcuts for each editor screen.

# [shortcuts.main]
# [shortcuts.geometry]
# [shortcuts.tiles]
# [shortcuts.cameras]
# [shortcuts.light]
# [shortcuts.effects]
# [shortcuts.props]
